# ガウス・ジョルダン法
***

In [1]:
import math
import numpy as np

n: 次数  
A: とりあえずの配列

In [46]:
n = 4
A = np.asarray([[1,1,0,3,2],[3,1,-9,-4,1],[-1,1,5,2,7],[3,2,-1,8,3]], dtype=np.float64)

In [47]:
for k in range(n):
    f = A[k, k]
    for p in range(k, n+1):
        A[k, p] = A[k, p] / f
    for q in range(n):
        g = A[q, k]
        if(q != k):
            for r in range(k, n+1):
                A[q, r] = A[q, r] -g *A[k, r]
    print(A)

[[  1.   1.   0.   3.   2.]
 [  0.  -2.  -9. -13.  -5.]
 [  0.   2.   5.   5.   9.]
 [  0.  -1.  -1.  -1.  -3.]]
[[ 1.   0.  -4.5 -3.5 -0.5]
 [ 0.   1.   4.5  6.5  2.5]
 [ 0.   0.  -4.  -8.   4. ]
 [ 0.   0.   3.5  5.5 -0.5]]
[[ 1.   0.   0.   5.5 -5. ]
 [ 0.   1.   0.  -2.5  7. ]
 [ 0.   0.   1.   2.  -1. ]
 [ 0.   0.   0.  -1.5  3. ]]
[[ 1.  0.  0.  0.  6.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0.  3.]
 [ 0.  0.  0.  1. -2.]]
